### ISSUE TITLE
Telegram-config

### ISSUE THREAD

**Issue by shrutipadole** [rahiel/supervisor-alert#7]
Hey, I tried to run supervisor-alert --configure
but i got an error saying 

Traceback (most recent call last):
  File "/usr/local/bin/supervisor-alert", line 11, in <module>
    load_entry_point('supervisor-alert==0.6.2', 'console_scripts', 'supervisor-alert')()
  File "/usr/local/lib/python3.5/dist-packages/supervisor_alert.py", line 42, in main
    return configure()
  File "/usr/local/lib/python3.5/dist-packages/supervisor_alert.py", line 132, in configure
    check_call(["telegram-send", "--configure"] + telegram_conf_args)
  File "/usr/lib/python3.5/subprocess.py", line 576, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)

Exactly what is the config supposed to look like

**Comment by rahiel** [comment]
Did you do the configuration with root permissions?

> Exactly what is the config supposed to look like

The configuration is described in the README: https://github.com/rahiel/supervisor-alert#manual-configuration
